wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: lightning
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1677171592.57654
    t:
      1:
      - 1
      - 9
      - 41
      - 50
      - 55
      2:
      - 1
      - 9
      - 41
      - 50
      - 55
      3:
      - 2
      - 23
      4: 3.9.12
      5: 0.13.10
      8:
      - 1
      - 3
      - 5
