wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1659320505
    t:
      1:
      - 55
      4: 3.9.12
      5: 0.12.21
      8:
      - 1
      - 3
      - 5
